In [1]:
import sys
sys.path.append("../new_way")

import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"

In [2]:
from api import vqvae_training

In [5]:
%%time

vqvae_training(model_route=r"/export/usuarios01/icmora/deploymentVQVAE/deployment-VQVAE/ignore/results/training/try2", 
               data_route=r"/export/usuarios01/icmora/deploymentVQVAE/deployment-VQVAE/ignore/merged.csv",
               hyperparameters = {"num_epochs_vqvae":40, "train_batch_size":256}
)

Model set to train on GPU: 0 for model: a0_1767983784 started. Preparing data loaders.

self.dataset.columns =
array(['user', 'date_time', 'service', 'sleep_start', 'location_distance',
       'location_time_home', 'sleep_duration', 'activity_walking',
       'app_usage_total', 'location_clusters_count', 'steps_steps_total',
       'weekend', 'practiced_sport', 'steps_0', 'steps_1', 'steps_2',
       'steps_3', 'steps_4', 'steps_5', 'steps_6', 'steps_7', 'steps_8',
       'steps_9', 'steps_10', 'steps_11', 'steps_12', 'steps_13',
       'steps_14', 'steps_15', 'steps_16', 'steps_17', 'steps_18',
       'steps_19', 'steps_20', 'steps_21', 'steps_22', 'steps_23',
       'steps_24', 'steps_25', 'steps_26', 'steps_27', 'steps_28',
       'steps_29', 'steps_30', 'steps_31', 'steps_32', 'steps_33',
       'steps_34', 'steps_35', 'steps_36', 'steps_37', 'steps_38',
       'steps_39', 'steps_40', 'steps_41', 'steps_42', 'steps_43',
       'steps_44', 'steps_45', 'steps_46', 'steps_47'], dtype=

/export/usuarios01/icmora/deploymentVQVAE/deployment-VQVAE/notebooks/../new_way/api_utils.py:708: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  bce_loss_functions = [torch.nn.BCEWithLogitsLoss(pos_weight=torch.tensor(pos_weights[i], device=device), reduction="none")


Conf Matrix [XO] - Phase: train Var: 8:
[[692 788]
 [263 324]]
Conf Matrix [XSM] - Phase: train Var: 8:
[[90 82]
 [32 33]]
Conf Matrix [XO] - Phase: train Var: 9:
[[843 766]
 [227 237]]
Conf Matrix [XSM] - Phase: train Var: 9:
[[103  77]
 [ 30  21]]
[train]   <loss> reco: 4.7255 | latent: 0.9745 | overall: 4.9691

[train] - Var 0 (mse_xo): 140585648.0000
[train] - Var 0 (rmse_xo): 11856.8818
[train] - Var 0 (mae_xo): 9391.7773
[train] - Var 0 (mse_xsm): 180765472.0000
[train] - Var 0 (rmse_xsm): 13444.9053
[train] - Var 0 (mae_xsm): 11441.5918

[train] - Var 1 (mse_xo): 22806263758848.0000
[train] - Var 1 (rmse_xo): 4775590.5000
[train] - Var 1 (mae_xo): 603433.2500
[train] - Var 1 (mse_xsm): 301190656.0000
[train] - Var 1 (rmse_xsm): 17354.8457
[train] - Var 1 (mae_xsm): 9248.3623

[train] - Var 2 (mse_xo): 538664.5000
[train] - Var 2 (rmse_xo): 733.9377
[train] - Var 2 (mae_xo): 548.8661
[train] - Var 2 (mse_xsm): 483869.6250
[train] - Var 2 (rmse_xsm): 695.6074
[train] - Var 2 (mae_

/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XO] - Phase: val Var: 8:
[[252   0]
 [ 99   0]]


/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XSM] - Phase: val Var: 8:
[[26  0]
 [ 7  0]]


/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XO] - Phase: val Var: 9:
[[230   0]
 [110   0]]


/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XSM] - Phase: val Var: 9:
[[24  0]
 [20  0]]
  [val]   <loss> reco: 2.7187 | latent: 0.0625 | overall: 2.7344

[val] - Var 0 (mse_xo): 36324624.0000
[val] - Var 0 (rmse_xo): 6026.9912
[val] - Var 0 (mae_xo): 4257.7979
[val] - Var 0 (mse_xsm): 30647774.0000
[val] - Var 0 (rmse_xsm): 5536.0430
[val] - Var 0 (mae_xsm): 4188.9111

[val] - Var 1 (mse_xo): 534831424.0000
[val] - Var 1 (rmse_xo): 23126.4219
[val] - Var 1 (mae_xo): 12177.4766
[val] - Var 1 (mse_xsm): 141768016.0000
[val] - Var 1 (rmse_xsm): 11906.6377
[val] - Var 1 (mae_xsm): 8351.4844

[val] - Var 2 (mse_xo): 190707.2656
[val] - Var 2 (rmse_xo): 436.7004
[val] - Var 2 (mae_xo): 365.0393
[val] - Var 2 (mse_xsm): 376365.6875
[val] - Var 2 (rmse_xsm): 613.4865
[val] - Var 2 (mae_xsm): 480.0676

[val] - Var 3 (mse_xo): 83244776.0000
[val] - Var 3 (rmse_xo): 9123.8574
[val] - Var 3 (mae_xo): 7213.2495
[val] - Var 3 (mse_xsm): 53281636.0000
[val] - Var 3 (rmse_xsm): 7299.4272
[val] - Var 3 (mae_xsm): 5899.9082

[val] -

/export/usuarios01/icmora/deploymentVQVAE/deployment-VQVAE/notebooks/../new_way/api_utils.py:558: RuntimeWarning: overflow encountered in power
  metrics[idx]["mse_xo"] = np.nanmean(np.power(


Conf Matrix [XO] - Phase: train Var: 8:
[[582 882]
 [186 393]]
Conf Matrix [XSM] - Phase: train Var: 8:
[[ 71 125]
 [ 28  37]]
Conf Matrix [XO] - Phase: train Var: 9:
[[720 732]
 [336 282]]
Conf Matrix [XSM] - Phase: train Var: 9:
[[85 80]
 [35 34]]
[train]   <loss> reco: 4.6042 | latent: 0.3311 | overall: 4.6869

[train] - Var 0 (mse_xo): 124771688.0000
[train] - Var 0 (rmse_xo): 11170.1250
[train] - Var 0 (mae_xo): 8537.4307
[train] - Var 0 (mse_xsm): 158223904.0000
[train] - Var 0 (rmse_xsm): 12578.7080
[train] - Var 0 (mae_xsm): 10463.8926

[train] - Var 1 (mse_xo): 805281398784.0000
[train] - Var 1 (rmse_xo): 897374.7500
[train] - Var 1 (mae_xo): 92398.5312
[train] - Var 1 (mse_xsm): 1227766912.0000
[train] - Var 1 (rmse_xsm): 35039.5039
[train] - Var 1 (mae_xsm): 16287.6973

[train] - Var 2 (mse_xo): 654180.8125
[train] - Var 2 (rmse_xo): 808.8145
[train] - Var 2 (mae_xo): 562.3243
[train] - Var 2 (mse_xsm): 460171.6562
[train] - Var 2 (rmse_xsm): 678.3596
[train] - Var 2 (mae_xs

/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XSM] - Phase: val Var: 9:
[[25  0]
 [16  0]]
  [val]   <loss> reco: 2.6737 | latent: 0.0803 | overall: 2.6938

[val] - Var 0 (mse_xo): 37951744.0000
[val] - Var 0 (rmse_xo): 6160.4985
[val] - Var 0 (mae_xo): 4333.4346
[val] - Var 0 (mse_xsm): 30670124.0000
[val] - Var 0 (rmse_xsm): 5538.0615
[val] - Var 0 (mae_xsm): 4932.1250

[val] - Var 1 (mse_xo): 475238144.0000
[val] - Var 1 (rmse_xo): 21799.9570
[val] - Var 1 (mae_xo): 11344.2100
[val] - Var 1 (mse_xsm): 898987648.0000
[val] - Var 1 (rmse_xsm): 29983.1230
[val] - Var 1 (mae_xsm): 17885.6875

[val] - Var 2 (mse_xo): 199369.8906
[val] - Var 2 (rmse_xo): 446.5085
[val] - Var 2 (mae_xo): 368.0917
[val] - Var 2 (mse_xsm): 120410.0156
[val] - Var 2 (rmse_xsm): 347.0015
[val] - Var 2 (mae_xsm): 347.0015

[val] - Var 3 (mse_xo): 74230504.0000
[val] - Var 3 (rmse_xo): 8615.7129
[val] - Var 3 (mae_xo): 6863.1577
[val] - Var 3 (mse_xsm): 116930040.0000
[val] - Var 3 (rmse_xsm): 10813.4199
[val] - Var 3 (mae_xsm): 8236.9551

[val

/export/usuarios01/icmora/deploymentVQVAE/deployment-VQVAE/notebooks/../new_way/api_utils.py:558: RuntimeWarning: overflow encountered in power
  metrics[idx]["mse_xo"] = np.nanmean(np.power(


Conf Matrix [XO] - Phase: train Var: 8:
[[719 777]
 [184 392]]
Conf Matrix [XSM] - Phase: train Var: 8:
[[81 83]
 [41 27]]
Conf Matrix [XO] - Phase: train Var: 9:
[[1065  497]
 [ 251  256]]
Conf Matrix [XSM] - Phase: train Var: 9:
[[135  49]
 [ 27  24]]
[train]   <loss> reco: 4.4391 | latent: 0.3046 | overall: 4.5153

[train] - Var 0 (mse_xo): 126217112.0000
[train] - Var 0 (rmse_xo): 11234.6387
[train] - Var 0 (mae_xo): 8757.5986
[train] - Var 0 (mse_xsm): 113881296.0000
[train] - Var 0 (rmse_xsm): 10671.5176
[train] - Var 0 (mae_xsm): 7667.9370

[train] - Var 1 (mse_xo): 1516229219057664.0000
[train] - Var 1 (rmse_xo): 38938788.0000
[train] - Var 1 (mae_xo): 3979982.5000
[train] - Var 1 (mse_xsm): 56761924.0000
[train] - Var 1 (rmse_xsm): 7534.0508
[train] - Var 1 (mae_xsm): 5482.8291

[train] - Var 2 (mse_xo): 287884.3438
[train] - Var 2 (rmse_xo): 536.5485
[train] - Var 2 (mae_xo): 390.1141
[train] - Var 2 (mse_xsm): 238648.2500
[train] - Var 2 (rmse_xsm): 488.5164
[train] - Var 2 

/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XSM] - Phase: val Var: 9:
[[23  0]
 [14  0]]
  [val]   <loss> reco: 2.8433 | latent: 0.0798 | overall: 2.8633

[val] - Var 0 (mse_xo): 43995724.0000
[val] - Var 0 (rmse_xo): 6632.9272
[val] - Var 0 (mae_xo): 4515.7046
[val] - Var 0 (mse_xsm): 19298854.0000
[val] - Var 0 (rmse_xsm): 4393.0459
[val] - Var 0 (mae_xsm): 4165.9844

[val] - Var 1 (mse_xo): 443445312.0000
[val] - Var 1 (rmse_xo): 21058.1406
[val] - Var 1 (mae_xo): 11708.8438
[val] - Var 1 (mse_xsm): 703844032.0000
[val] - Var 1 (rmse_xsm): 26530.0586
[val] - Var 1 (mae_xsm): 13461.8867

[val] - Var 2 (mse_xo): 177475.9062
[val] - Var 2 (rmse_xo): 421.2789
[val] - Var 2 (mae_xo): 353.6078
[val] - Var 2 (mse_xsm): 272689.6875
[val] - Var 2 (rmse_xsm): 522.1970
[val] - Var 2 (mae_xsm): 374.1586

[val] - Var 3 (mse_xo): 76050040.0000
[val] - Var 3 (rmse_xo): 8720.6670
[val] - Var 3 (mae_xo): 6934.9175
[val] - Var 3 (mse_xsm): 98738232.0000
[val] - Var 3 (rmse_xsm): 9936.7109
[val] - Var 3 (mae_xsm): 7591.5537

[val] 

/export/usuarios01/icmora/deploymentVQVAE/deployment-VQVAE/notebooks/../new_way/api_utils.py:558: RuntimeWarning: overflow encountered in power
  metrics[idx]["mse_xo"] = np.nanmean(np.power(


Conf Matrix [XO] - Phase: train Var: 8:
[[881 593]
 [145 456]]
Conf Matrix [XSM] - Phase: train Var: 8:
[[103  81]
 [ 19  26]]
Conf Matrix [XO] - Phase: train Var: 9:
[[1050  523]
 [ 225  278]]
Conf Matrix [XSM] - Phase: train Var: 9:
[[112  61]
 [ 29  26]]
[train]   <loss> reco: 3.7222 | latent: 0.3042 | overall: 3.7982

[train] - Var 0 (mse_xo): 88084200.0000
[train] - Var 0 (rmse_xo): 9385.3184
[train] - Var 0 (mae_xo): 7337.8433
[train] - Var 0 (mse_xsm): 68076256.0000
[train] - Var 0 (rmse_xsm): 8250.8340
[train] - Var 0 (mae_xsm): 6495.2476

[train] - Var 1 (mse_xo): 7685458624512.0000
[train] - Var 1 (rmse_xo): 2772266.0000
[train] - Var 1 (mae_xo): 454808.3438
[train] - Var 1 (mse_xsm): 408593472.0000
[train] - Var 1 (rmse_xsm): 20213.6953
[train] - Var 1 (mae_xsm): 13754.2314

[train] - Var 2 (mse_xo): 435757.9688
[train] - Var 2 (rmse_xo): 660.1197
[train] - Var 2 (mae_xo): 405.5623
[train] - Var 2 (mse_xsm): 1018732.4375
[train] - Var 2 (rmse_xsm): 1009.3228
[train] - Var 2 

/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XO] - Phase: val Var: 9:
[[177   0]
 [169   0]]
Conf Matrix [XSM] - Phase: val Var: 9:
[[18  0]
 [20  0]]
  [val]   <loss> reco: 2.8302 | latent: 0.0871 | overall: 2.8520

[val] - Var 0 (mse_xo): 48327328.0000
[val] - Var 0 (rmse_xo): 6951.7861
[val] - Var 0 (mae_xo): 5112.4023
[val] - Var 0 (mse_xsm): 33838276.0000
[val] - Var 0 (rmse_xsm): 5817.0679
[val] - Var 0 (mae_xsm): 3434.4568

[val] - Var 1 (mse_xo): 390187232.0000
[val] - Var 1 (rmse_xo): 19753.1582
[val] - Var 1 (mae_xo): 9811.4170
[val] - Var 1 (mse_xsm): 395971616.0000
[val] - Var 1 (rmse_xsm): 19899.0352
[val] - Var 1 (mae_xsm): 12276.2119

[val] - Var 2 (mse_xo): 111712.1094
[val] - Var 2 (rmse_xo): 334.2336
[val] - Var 2 (mae_xo): 256.4908
[val] - Var 2 (mse_xsm): 158027.0625
[val] - Var 2 (rmse_xsm): 397.5262
[val] - Var 2 (mae_xsm): 397.5262

[val] - Var 3 (mse_xo): 97036552.0000
[val] - Var 3 (rmse_xo): 9850.7129
[val] - Var 3 (mae_xo): 7845.3677
[val] - Var 3 (mse_xsm): 87154336.0000
[val] - Var 3 (rms

/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XSM] - Phase: val Var: 9:
[[25  0]
 [10  0]]
  [val]   <loss> reco: 3.0974 | latent: 0.0776 | overall: 3.1168

[val] - Var 0 (mse_xo): 71989464.0000
[val] - Var 0 (rmse_xo): 8484.6602
[val] - Var 0 (mae_xo): 6094.2437
[val] - Var 0 (mse_xsm): 49685800.0000
[val] - Var 0 (rmse_xsm): 7048.8154
[val] - Var 0 (mae_xsm): 5278.3862

[val] - Var 1 (mse_xo): 563756480.0000
[val] - Var 1 (rmse_xo): 23743.5566
[val] - Var 1 (mae_xo): 12642.3916
[val] - Var 1 (mse_xsm): 59277160.0000
[val] - Var 1 (rmse_xsm): 7699.1660
[val] - Var 1 (mae_xsm): 5473.8340

[val] - Var 2 (mse_xo): 192165.8594
[val] - Var 2 (rmse_xo): 438.3673
[val] - Var 2 (mae_xo): 363.4413
[val] - Var 2 (mse_xsm): 44572.6328
[val] - Var 2 (rmse_xsm): 211.1223
[val] - Var 2 (mae_xsm): 211.1223

[val] - Var 3 (mse_xo): 97355328.0000
[val] - Var 3 (rmse_xo): 9866.8799
[val] - Var 3 (mae_xo): 7642.6113
[val] - Var 3 (mse_xsm): 48573124.0000
[val] - Var 3 (rmse_xsm): 6969.4424
[val] - Var 3 (mae_xsm): 5326.1079

[val] - Va

/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XO] - Phase: val Var: 9:
[[178   0]
 [162   0]]


/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XSM] - Phase: val Var: 9:
[[27  0]
 [17  0]]
  [val]   <loss> reco: 2.8479 | latent: 0.0689 | overall: 2.8651

[val] - Var 0 (mse_xo): 35850060.0000
[val] - Var 0 (rmse_xo): 5987.4922
[val] - Var 0 (mae_xo): 4676.2178
[val] - Var 0 (mse_xsm): 35481212.0000
[val] - Var 0 (rmse_xsm): 5956.6108
[val] - Var 0 (mae_xsm): 4670.2681

[val] - Var 1 (mse_xo): 323721952.0000
[val] - Var 1 (rmse_xo): 17992.2754
[val] - Var 1 (mae_xo): 9065.8438
[val] - Var 1 (mse_xsm): 907971392.0000
[val] - Var 1 (rmse_xsm): 30132.5645
[val] - Var 1 (mae_xsm): 15643.6182

[val] - Var 2 (mse_xo): 105197.4531
[val] - Var 2 (rmse_xo): 324.3416
[val] - Var 2 (mae_xo): 250.9901
[val] - Var 2 (mse_xsm): 95099.4609
[val] - Var 2 (rmse_xsm): 308.3820
[val] - Var 2 (mae_xsm): 269.6283

[val] - Var 3 (mse_xo): 99415768.0000
[val] - Var 3 (rmse_xo): 9970.7461
[val] - Var 3 (mae_xo): 8053.1152
[val] - Var 3 (mse_xsm): 68480536.0000
[val] - Var 3 (rmse_xsm): 8275.2969
[val] - Var 3 (mae_xsm): 6915.2607

[val] - 

/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XO] - Phase: val Var: 9:
[[229   0]
 [118   0]]
Conf Matrix [XSM] - Phase: val Var: 9:
[[22  0]
 [15  0]]
  [val]   <loss> reco: 3.1998 | latent: 0.0585 | overall: 3.2144

[val] - Var 0 (mse_xo): 45838144.0000
[val] - Var 0 (rmse_xo): 6770.3872
[val] - Var 0 (mae_xo): 5080.4751
[val] - Var 0 (mse_xsm): 57699292.0000
[val] - Var 0 (rmse_xsm): 7596.0049
[val] - Var 0 (mae_xsm): 5719.3506

[val] - Var 1 (mse_xo): 533422560.0000
[val] - Var 1 (rmse_xo): 23095.9434
[val] - Var 1 (mae_xo): 12612.0381
[val] - Var 1 (mse_xsm): 70779184.0000
[val] - Var 1 (rmse_xsm): 8413.0361
[val] - Var 1 (mae_xsm): 5583.0288

[val] - Var 2 (mse_xo): 162799.2031
[val] - Var 2 (rmse_xo): 403.4838
[val] - Var 2 (mae_xo): 333.4725
[val] - Var 2 (mse_xsm): 12696.4092
[val] - Var 2 (rmse_xsm): 112.6783
[val] - Var 2 (mae_xsm): 112.6783

[val] - Var 3 (mse_xo): 77053456.0000
[val] - Var 3 (rmse_xo): 8778.0098
[val] - Var 3 (mae_xo): 6939.0752
[val] - Var 3 (mse_xsm): 106931392.0000
[val] - Var 3 (rmse_

/export/usuarios01/icmora/deploymentVQVAE/deployment-VQVAE/notebooks/../new_way/api_utils.py:558: RuntimeWarning: overflow encountered in power
  metrics[idx]["mse_xo"] = np.nanmean(np.power(


Conf Matrix [XO] - Phase: train Var: 8:
[[815 681]
 [198 384]]
Conf Matrix [XSM] - Phase: train Var: 8:
[[81 76]
 [28 41]]
Conf Matrix [XO] - Phase: train Var: 9:
[[788 838]
 [ 42 394]]
Conf Matrix [XSM] - Phase: train Var: 9:
[[86 98]
 [11 47]]
[train]   <loss> reco: 2.9385 | latent: 0.3295 | overall: 3.0209

[train] - Var 0 (mse_xo): 74915000.0000
[train] - Var 0 (rmse_xo): 8655.3447
[train] - Var 0 (mae_xo): 7101.8550
[train] - Var 0 (mse_xsm): 71092928.0000
[train] - Var 0 (rmse_xsm): 8431.6621
[train] - Var 0 (mae_xsm): 6912.7515

[train] - Var 1 (mse_xo): 8716991488.0000
[train] - Var 1 (rmse_xo): 93364.8281
[train] - Var 1 (mae_xo): 50970.4570
[train] - Var 1 (mse_xsm): 4181397504.0000
[train] - Var 1 (rmse_xsm): 64663.7266
[train] - Var 1 (mae_xsm): 42453.6602

[train] - Var 2 (mse_xo): 431321.3750
[train] - Var 2 (rmse_xo): 656.7506
[train] - Var 2 (mae_xo): 569.4146
[train] - Var 2 (mse_xsm): 337162.3438
[train] - Var 2 (rmse_xsm): 580.6568
[train] - Var 2 (mae_xsm): 508.4183

/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XO] - Phase: val Var: 9:
[[227   0]
 [120   0]]
Conf Matrix [XSM] - Phase: val Var: 9:
[[23  0]
 [14  0]]
  [val]   <loss> reco: 3.3234 | latent: 0.0449 | overall: 3.3346

[val] - Var 0 (mse_xo): 79943552.0000
[val] - Var 0 (rmse_xo): 8941.1162
[val] - Var 0 (mae_xo): 6487.0791
[val] - Var 0 (mse_xsm): 56500144.0000
[val] - Var 0 (rmse_xsm): 7516.6577
[val] - Var 0 (mae_xsm): 5678.2974

[val] - Var 1 (mse_xo): 552031936.0000
[val] - Var 1 (rmse_xo): 23495.3594
[val] - Var 1 (mae_xo): 12664.9893
[val] - Var 1 (mse_xsm): 519207744.0000
[val] - Var 1 (rmse_xsm): 22786.1309
[val] - Var 1 (mae_xsm): 13167.5996

[val] - Var 2 (mse_xo): 160451.9062
[val] - Var 2 (rmse_xo): 400.5645
[val] - Var 2 (mae_xo): 328.4854
[val] - Var 2 (mse_xsm): 0.0000
[val] - Var 2 (rmse_xsm): 0.0000
[val] - Var 2 (mae_xsm): 0.0000

[val] - Var 3 (mse_xo): 82303216.0000
[val] - Var 3 (rmse_xo): 9072.1123
[val] - Var 3 (mae_xo): 7031.6357
[val] - Var 3 (mse_xsm): 58027372.0000
[val] - Var 3 (rmse_xsm): 

/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XSM] - Phase: val Var: 9:
[[18  0]
 [18  0]]
  [val]   <loss> reco: 3.1528 | latent: 0.0445 | overall: 3.1639

[val] - Var 0 (mse_xo): 68936064.0000
[val] - Var 0 (rmse_xo): 8302.7744
[val] - Var 0 (mae_xo): 5973.7769
[val] - Var 0 (mse_xsm): 86213304.0000
[val] - Var 0 (rmse_xsm): 9285.1123
[val] - Var 0 (mae_xsm): 8012.6562

[val] - Var 1 (mse_xo): 457008992.0000
[val] - Var 1 (rmse_xo): 21377.7695
[val] - Var 1 (mae_xo): 10371.0723
[val] - Var 1 (mse_xsm): 162057984.0000
[val] - Var 1 (rmse_xsm): 12730.1992
[val] - Var 1 (mae_xsm): 10694.5127

[val] - Var 2 (mse_xo): 86508.2031
[val] - Var 2 (rmse_xo): 294.1228
[val] - Var 2 (mae_xo): 228.3853
[val] - Var 2 (mse_xsm): 221180.8906
[val] - Var 2 (rmse_xsm): 470.2987
[val] - Var 2 (mae_xsm): 465.8121

[val] - Var 3 (mse_xo): 94243528.0000
[val] - Var 3 (rmse_xo): 9707.9102
[val] - Var 3 (mae_xo): 7605.6606
[val] - Var 3 (mse_xsm): 61328296.0000
[val] - Var 3 (rmse_xsm): 7831.2383
[val] - Var 3 (mae_xsm): 6562.7046

[val] -

/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XSM] - Phase: val Var: 9:
[[19  0]
 [21  0]]
  [val]   <loss> reco: 3.2114 | latent: 0.0445 | overall: 3.2225

[val] - Var 0 (mse_xo): 69536544.0000
[val] - Var 0 (rmse_xo): 8338.8574
[val] - Var 0 (mae_xo): 6142.3896
[val] - Var 0 (mse_xsm): 64987920.0000
[val] - Var 0 (rmse_xsm): 8061.5083
[val] - Var 0 (mae_xsm): 5919.3511

[val] - Var 1 (mse_xo): 429089504.0000
[val] - Var 1 (rmse_xo): 20714.4766
[val] - Var 1 (mae_xo): 10383.1846
[val] - Var 1 (mse_xsm): 651490560.0000
[val] - Var 1 (rmse_xsm): 25524.3125
[val] - Var 1 (mae_xsm): 10849.4004

[val] - Var 2 (mse_xo): 84297.2578
[val] - Var 2 (rmse_xo): 290.3399
[val] - Var 2 (mae_xo): 224.0430
[val] - Var 2 (mse_xsm): 48221.7070
[val] - Var 2 (rmse_xsm): 219.5944
[val] - Var 2 (mae_xsm): 209.9999

[val] - Var 3 (mse_xo): 92447272.0000
[val] - Var 3 (rmse_xo): 9614.9502
[val] - Var 3 (mae_xo): 7814.8291
[val] - Var 3 (mse_xsm): 138298704.0000
[val] - Var 3 (rmse_xsm): 11760.0469
[val] - Var 3 (mae_xsm): 7776.9204

[val] 

/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XO] - Phase: val Var: 9:
[[209   1]
 [137   0]]


/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XSM] - Phase: val Var: 9:
[[26  0]
 [11  0]]
  [val]   <loss> reco: 3.1387 | latent: 0.0474 | overall: 3.1505

[val] - Var 0 (mse_xo): 40943528.0000
[val] - Var 0 (rmse_xo): 6398.7129
[val] - Var 0 (mae_xo): 4565.5415
[val] - Var 0 (mse_xsm): 53575952.0000
[val] - Var 0 (rmse_xsm): 7319.5596
[val] - Var 0 (mae_xsm): 5492.3110

[val] - Var 1 (mse_xo): 400050496.0000
[val] - Var 1 (rmse_xo): 20001.2617
[val] - Var 1 (mae_xo): 10897.1338
[val] - Var 1 (mse_xsm): 1503680512.0000
[val] - Var 1 (rmse_xsm): 38777.3203
[val] - Var 1 (mae_xsm): 25697.9512

[val] - Var 2 (mse_xo): 141962.1250
[val] - Var 2 (rmse_xo): 376.7786
[val] - Var 2 (mae_xo): 312.9205
[val] - Var 2 (mse_xsm): 32667.0684
[val] - Var 2 (rmse_xsm): 180.7403
[val] - Var 2 (mae_xsm): 176.3202

[val] - Var 3 (mse_xo): 79087416.0000
[val] - Var 3 (rmse_xo): 8893.1104
[val] - Var 3 (mae_xo): 7067.2046
[val] - Var 3 (mse_xsm): 69308184.0000
[val] - Var 3 (rmse_xsm): 8325.1533
[val] - Var 3 (mae_xsm): 6807.2280

[val] 

/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XSM] - Phase: val Var: 8:
[[16  0]
 [10  0]]
Conf Matrix [XO] - Phase: val Var: 9:
[[210  12]
 [115   3]]
Conf Matrix [XSM] - Phase: val Var: 9:
[[27  1]
 [16  0]]
  [val]   <loss> reco: 3.1667 | latent: 0.0509 | overall: 3.1794

[val] - Var 0 (mse_xo): 37986976.0000
[val] - Var 0 (rmse_xo): 6163.3574
[val] - Var 0 (mae_xo): 4365.4805
[val] - Var 0 (mse_xsm): 57475252.0000
[val] - Var 0 (rmse_xsm): 7581.2437
[val] - Var 0 (mae_xsm): 5146.4229

[val] - Var 1 (mse_xo): 530899904.0000
[val] - Var 1 (rmse_xo): 23041.2656
[val] - Var 1 (mae_xo): 12291.2715
[val] - Var 1 (mse_xsm): 29711810.0000
[val] - Var 1 (rmse_xsm): 5450.8540
[val] - Var 1 (mae_xsm): 3755.3154

[val] - Var 2 (mse_xo): 195902.6406
[val] - Var 2 (rmse_xo): 442.6089
[val] - Var 2 (mae_xo): 367.8720
[val] - Var 2 (mse_xsm): 39852.3594
[val] - Var 2 (rmse_xsm): 199.6306
[val] - Var 2 (mae_xsm): 180.0000

[val] - Var 3 (mse_xo): 74286272.0000
[val] - Var 3 (rmse_xo): 8618.9482
[val] - Var 3 (mae_xo): 6832.8032
[v

/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XO] - Phase: val Var: 9:
[[ 41 143]
 [ 24 136]]
Conf Matrix [XSM] - Phase: val Var: 9:
[[ 5 19]
 [ 2 14]]
  [val]   <loss> reco: 2.7540 | latent: 0.0555 | overall: 2.7679

[val] - Var 0 (mse_xo): 32359810.0000
[val] - Var 0 (rmse_xo): 5688.5684
[val] - Var 0 (mae_xo): 4073.5273
[val] - Var 0 (mse_xsm): 30501868.0000
[val] - Var 0 (rmse_xsm): 5522.8496
[val] - Var 0 (mae_xsm): 4212.4062

[val] - Var 1 (mse_xo): 367889536.0000
[val] - Var 1 (rmse_xo): 19180.4473
[val] - Var 1 (mae_xo): 9176.6299
[val] - Var 1 (mse_xsm): 167620944.0000
[val] - Var 1 (rmse_xsm): 12946.8506
[val] - Var 1 (mae_xsm): 7836.0723

[val] - Var 2 (mse_xo): 87530.9688
[val] - Var 2 (rmse_xo): 295.8563
[val] - Var 2 (mae_xo): 236.8595
[val] - Var 2 (mse_xsm): 213119.8750
[val] - Var 2 (rmse_xsm): 461.6491
[val] - Var 2 (mae_xsm): 361.7704

[val] - Var 3 (mse_xo): 101063840.0000
[val] - Var 3 (rmse_xo): 10053.0518
[val] - Var 3 (mae_xo): 7977.8247
[val] - Var 3 (mse_xsm): 53878652.0000
[val] - Var 3 (rms

/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XO] - Phase: val Var: 9:
[[ 54 126]
 [ 18 149]]
Conf Matrix [XSM] - Phase: val Var: 9:
[[ 4 13]
 [ 4 16]]
  [val]   <loss> reco: 2.5895 | latent: 0.0558 | overall: 2.6034

[val] - Var 0 (mse_xo): 43660788.0000
[val] - Var 0 (rmse_xo): 6607.6309
[val] - Var 0 (mae_xo): 4986.5913
[val] - Var 0 (mse_xsm): 161168128.0000
[val] - Var 0 (rmse_xsm): 12695.2012
[val] - Var 0 (mae_xsm): 9990.6533

[val] - Var 1 (mse_xo): 277340352.0000
[val] - Var 1 (rmse_xo): 16653.5391
[val] - Var 1 (mae_xo): 7805.0259
[val] - Var 1 (mse_xsm): 617472640.0000
[val] - Var 1 (rmse_xsm): 24848.9961
[val] - Var 1 (mae_xsm): 12309.7998

[val] - Var 2 (mse_xo): 86389.7188
[val] - Var 2 (rmse_xo): 293.9213
[val] - Var 2 (mae_xo): 229.4098
[val] - Var 2 (mse_xsm): 124703.5625
[val] - Var 2 (rmse_xsm): 353.1339
[val] - Var 2 (mae_xsm): 353.1339

[val] - Var 3 (mse_xo): 102142936.0000
[val] - Var 3 (rmse_xo): 10106.5791
[val] - Var 3 (mae_xo): 8065.4893
[val] - Var 3 (mse_xsm): 128085384.0000
[val] - Var 3 

/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XO] - Phase: val Var: 9:
[[ 52 124]
 [ 14 146]]
Conf Matrix [XSM] - Phase: val Var: 9:
[[ 5 15]
 [ 4 24]]
  [val]   <loss> reco: 2.5342 | latent: 0.0560 | overall: 2.5481

[val] - Var 0 (mse_xo): 45309156.0000
[val] - Var 0 (rmse_xo): 6731.2075
[val] - Var 0 (mae_xo): 5121.7324
[val] - Var 0 (mse_xsm): 76262520.0000
[val] - Var 0 (rmse_xsm): 8732.8418
[val] - Var 0 (mae_xsm): 5743.4199

[val] - Var 1 (mse_xo): 276021568.0000
[val] - Var 1 (rmse_xo): 16613.8965
[val] - Var 1 (mae_xo): 8006.4673
[val] - Var 1 (mse_xsm): 674552384.0000
[val] - Var 1 (rmse_xsm): 25972.1465
[val] - Var 1 (mae_xsm): 14856.1201

[val] - Var 2 (mse_xo): 80776.1953
[val] - Var 2 (rmse_xo): 284.2115
[val] - Var 2 (mae_xo): 224.0582
[val] - Var 2 (mse_xsm): 161808.6719
[val] - Var 2 (rmse_xsm): 402.2545
[val] - Var 2 (mae_xsm): 329.6599

[val] - Var 3 (mse_xo): 111501864.0000
[val] - Var 3 (rmse_xo): 10559.4443
[val] - Var 3 (mae_xo): 8449.2588
[val] - Var 3 (mse_xsm): 51119944.0000
[val] - Var 3 (rm

In [23]:
%%time

vqvae_training(model_route=r"/export/usuarios01/icmora/deploymentVQVAE/deployment-VQVAE/ignore/results/training/try2", 
               data_route=r"/export/usuarios01/icmora/deploymentVQVAE/deployment-VQVAE/ignore/data_test/daily_summary_DC.csv",
               hyperparameters = {"num_epochs_vqvae":1, "train_batch_size":512}
)

Model set to train on GPU: 0 for model: a0_1767650043 started. Preparing data loaders.

self.dataset.columns =
array(['user', 'date_time', 'service', 'sleep_start', 'location_distance',
       'location_time_home', 'sleep_duration', 'activity_walking',
       'app_usage_total', 'location_clusters_count', 'steps_steps_total',
       'weekend', 'practiced_sport'], dtype=object)

self.dataset.dtypes =
user                                int64
date_time                  datetime64[ns]
service                            object
sleep_start                       float64
location_distance                 float64
location_time_home                float64
sleep_duration                    float64
activity_walking                  float64
app_usage_total                   float64
location_clusters_count           float64
steps_steps_total                 float64
weekend                             int64
practiced_sport                     int64
dtype: object

self.dataset.shape =
(9121, 13)


Sta

/export/usuarios01/icmora/deploymentVQVAE/deployment-VQVAE/notebooks/../new_way/api_utils.py:705: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  bce_loss_functions = [torch.nn.BCEWithLogitsLoss(pos_weight=torch.tensor(pos_weights[i], device=device), reduction="none")


Conf Matrix [XO] - Phase: train Var: 8:
[[753 812]
 [302 322]]
Conf Matrix [XSM] - Phase: train Var: 8:
[[81 95]
 [37 30]]
Conf Matrix [XO] - Phase: train Var: 9:
[[847 755]
 [272 315]]
Conf Matrix [XSM] - Phase: train Var: 9:
[[94 92]
 [31 26]]
[train]   <loss> reco: 4.2324 | latent: 0.9628 | overall: 4.4731

[train] - Var 0 (mse_xo): 159206624.0000
[train] - Var 0 (rmse_xo): 12617.7109
[train] - Var 0 (mae_xo): 10079.5117
[train] - Var 0 (mse_xsm): 129070032.0000
[train] - Var 0 (rmse_xsm): 11360.8994
[train] - Var 0 (mae_xsm): 9159.9746

[train] - Var 1 (mse_xo): 31776741376.0000
[train] - Var 1 (rmse_xo): 178260.3125
[train] - Var 1 (mae_xo): 43391.7227
[train] - Var 1 (mse_xsm): 21621442560.0000
[train] - Var 1 (rmse_xsm): 147042.3125
[train] - Var 1 (mae_xsm): 42597.2461

[train] - Var 2 (mse_xo): 307965.0312
[train] - Var 2 (rmse_xo): 554.9460
[train] - Var 2 (mae_xo): 444.4049
[train] - Var 2 (mse_xsm): 344037.5000
[train] - Var 2 (rmse_xsm): 586.5471
[train] - Var 2 (mae_xsm):

/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XO] - Phase: val Var: 8:
[[334   0]
 [128   0]]


/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XSM] - Phase: val Var: 8:
[[37  0]
 [13  0]]
Conf Matrix [XO] - Phase: val Var: 9:
[[361   3]
 [ 85   1]]


/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XSM] - Phase: val Var: 9:
[[41  0]
 [21  0]]
  [val]   <loss> reco: 2.3875 | latent: 0.1002 | overall: 2.4126

[val] - Var 0 (mse_xo): 67527208.0000
[val] - Var 0 (rmse_xo): 8217.4941
[val] - Var 0 (mae_xo): 6784.9097
[val] - Var 0 (mse_xsm): 43266296.0000
[val] - Var 0 (rmse_xsm): 6577.7119
[val] - Var 0 (mae_xsm): 5791.2412

[val] - Var 1 (mse_xo): 37491428.0000
[val] - Var 1 (rmse_xo): 6123.0244
[val] - Var 1 (mae_xo): 4113.4434
[val] - Var 1 (mse_xsm): 6078047.5000
[val] - Var 1 (rmse_xsm): 2465.3696
[val] - Var 1 (mae_xsm): 2439.0969

[val] - Var 2 (mse_xo): 61332.0703
[val] - Var 2 (rmse_xo): 247.6531
[val] - Var 2 (mae_xo): 208.2746
[val] - Var 2 (mse_xsm): 37484.6836
[val] - Var 2 (rmse_xsm): 193.6096
[val] - Var 2 (mae_xsm): 174.6748

[val] - Var 3 (mse_xo): 106704152.0000
[val] - Var 3 (rmse_xo): 10329.7705
[val] - Var 3 (mae_xo): 7917.8638
[val] - Var 3 (mse_xsm): 63939308.0000
[val] - Var 3 (rmse_xsm): 7996.2061
[val] - Var 3 (mae_xsm): 6506.9556

[val] - Var 4

/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XO] - Phase: test Var: 8:
[[331   0]
 [137   0]]


/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XSM] - Phase: test Var: 8:
[[35  0]
 [ 9  0]]
Conf Matrix [XO] - Phase: test Var: 9:
[[347   3]
 [109   1]]


/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XSM] - Phase: test Var: 9:
[[42  0]
 [10  0]]
CPU times: user 5.65 s, sys: 1.15 s, total: 6.8 s
Wall time: 10.2 s


In [3]:
%%time

vqvae_training(model_route="/export/usuarios01/icmora/deploymentVQVAE/api_test/results_finetune/fine_tune1", 
               data_route="~/data/eb2/daily_summary_eb2prod.csv",
               hyperparameters = {"num_epochs_vqvae":1, "train_batch_size":512}
)

/export/usuarios01/icmora/deploymentVQVAE/new_way/api_utils.py:144: DtypeWarning: Columns (55) have mixed types. Specify dtype option on import or set low_memory=False.
  df_ = pd.read_csv(original_data_path)


Model set to train on GPU: 0 for model: a0_1760967503 started. Preparing data loaders.

self.dataset.columns =
array(['user', 'date_time', 'service', 'sleep_start', 'location_distance',
       'location_time_home', 'sleep_duration', 'activity_walking',
       'app_usage_total', 'location_clusters_count', 'steps_steps_total',
       'weekend', 'practiced_sport'], dtype=object)

self.dataset.dtypes =
user                                int64
date_time                  datetime64[ns]
service                           float64
sleep_start                       float64
location_distance                 float64
location_time_home                float64
sleep_duration                    float64
activity_walking                  float64
app_usage_total                   float64
location_clusters_count           float64
steps_steps_total                 float64
weekend                             int64
practiced_sport                   float64
dtype: object

self.dataset.shape =
(164172, 13)


S

/export/usuarios01/icmora/deploymentVQVAE/new_way/api_utils.py:705: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  bce_loss_functions = [torch.nn.BCEWithLogitsLoss(pos_weight=torch.tensor(pos_weights[i], device=device), reduction="none")


Conf Matrix [XO] - Phase: train Var: 8:
[[23283  4783]
 [  916 10074]]
Conf Matrix [XSM] - Phase: train Var: 8:
[[2554  499]
 [ 531  752]]
Conf Matrix [XO] - Phase: train Var: 9:
[[14214  8969]
 [ 2259 13527]]
Conf Matrix [XSM] - Phase: train Var: 9:
[[1636 1018]
 [ 480 1289]]
[train]   <loss> reco: 1.1009 | latent: 0.2853 | overall: 1.1722

[train] - Var 0 (mse_xo): 13760683.0000
[train] - Var 0 (rmse_xo): 3709.5396
[train] - Var 0 (mae_xo): 2854.6248
[train] - Var 0 (mse_xsm): 43182136.0000
[train] - Var 0 (rmse_xsm): 6571.3115
[train] - Var 0 (mae_xsm): 5168.1787

[train] - Var 1 (mse_xo): 8752311296.0000
[train] - Var 1 (rmse_xo): 93553.7891
[train] - Var 1 (mae_xo): 12233.5557
[train] - Var 1 (mse_xsm): 483452384.0000
[train] - Var 1 (rmse_xsm): 21987.5508
[train] - Var 1 (mae_xsm): 11050.3965

[train] - Var 2 (mse_xo): 97501.8359
[train] - Var 2 (rmse_xo): 312.2528
[train] - Var 2 (mae_xo): 251.5490
[train] - Var 2 (mse_xsm): 117985.1016
[train] - Var 2 (rmse_xsm): 343.4896
[trai