In [2]:
import sys
sys.path.append("../new_way")

import os
os.environ["CUDA_VISIBLE_DEVICES"] = "1"

In [3]:
from api import vqvae_training

In [5]:
%%time

vqvae_training(model_route="/export/usuarios01/icmora/deploymentVQVAE-GitHub/uploadcode/vqvae-profiling/api_test/results_training/training_6", 
               data_route="~/data/eb2/daily_summary_eb2prod.csv",
               hyperparameters = {"num_epochs_vqvae":1, "train_batch_size":512}
)

/export/usuarios01/icmora/deploymentVQVAE-GitHub/uploadcode/vqvae-profiling/notebooks/../new_way/api_utils.py:144: DtypeWarning: Columns (55) have mixed types. Specify dtype option on import or set low_memory=False.
  df_ = pd.read_csv(original_data_path)


Model set to train on GPU: 0 for model: a0_1762863456 started. Preparing data loaders.

self.dataset.columns =
array(['user', 'date_time', 'service', 'sleep_start', 'location_distance',
       'location_time_home', 'sleep_duration', 'activity_walking',
       'app_usage_total', 'location_clusters_count', 'steps_steps_total',
       'weekend', 'practiced_sport'], dtype=object)

self.dataset.dtypes =
user                                int64
date_time                  datetime64[ns]
service                           float64
sleep_start                       float64
location_distance                 float64
location_time_home                float64
sleep_duration                    float64
activity_walking                  float64
app_usage_total                   float64
location_clusters_count           float64
steps_steps_total                 float64
weekend                             int64
practiced_sport                   float64
dtype: object

self.dataset.shape =
(161849, 13)


S

/export/usuarios01/icmora/deploymentVQVAE-GitHub/uploadcode/vqvae-profiling/notebooks/../new_way/api_utils.py:705: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  bce_loss_functions = [torch.nn.BCEWithLogitsLoss(pos_weight=torch.tensor(pos_weights[i], device=device), reduction="none")


Conf Matrix [XO] - Phase: train Var: 8:
[[13693 14286]
 [ 5812  5201]]
Conf Matrix [XSM] - Phase: train Var: 8:
[[1556 1611]
 [ 647  586]]
Conf Matrix [XO] - Phase: train Var: 9:
[[11436 12271]
 [ 7811  7573]]
Conf Matrix [XSM] - Phase: train Var: 9:
[[1233 1371]
 [ 825  872]]
[train]   <loss> reco: 3.7987 | latent: 0.9343 | overall: 4.0323

[train] - Var 0 (mse_xo): 122344960.0000
[train] - Var 0 (rmse_xo): 11060.9658
[train] - Var 0 (mae_xo): 8789.2051
[train] - Var 0 (mse_xsm): 131416840.0000
[train] - Var 0 (rmse_xsm): 11463.7188
[train] - Var 0 (mae_xsm): 9128.9531

[train] - Var 1 (mse_xo): 217288552742912.0000
[train] - Var 1 (rmse_xo): 14740711.0000
[train] - Var 1 (mae_xo): 499867.4375
[train] - Var 1 (mse_xsm): 6756149231616.0000
[train] - Var 1 (rmse_xsm): 2599259.2500
[train] - Var 1 (mae_xsm): 249027.4688

[train] - Var 2 (mse_xo): 523902.0000
[train] - Var 2 (rmse_xo): 723.8107
[train] - Var 2 (mae_xo): 533.7673
[train] - Var 2 (mse_xsm): 533972.1250
[train] - Var 2 (rmse

/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XO] - Phase: val Var: 8:
[[5322    0]
 [2050    0]]


/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XSM] - Phase: val Var: 8:
[[572   0]
 [248   0]]


/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XO] - Phase: val Var: 9:
[[4698    0]
 [2649    0]]


/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XSM] - Phase: val Var: 9:
[[543   0]
 [302   0]]


/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XO] - Phase: val Var: 8:
[[662   0]
 [259   0]]
Conf Matrix [XSM] - Phase: val Var: 8:
[[74  0]
 [29  0]]


/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XO] - Phase: val Var: 9:
[[630   0]
 [301   0]]


/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XSM] - Phase: val Var: 9:
[[56  0]
 [37  0]]
  [val]   <loss> reco: 2.0931 | latent: 0.1057 | overall: 2.1195

[val] - Var 0 (mse_xo): 53059235.7778
[val] - Var 0 (rmse_xo): 7256.1987
[val] - Var 0 (mae_xo): 5850.8530
[val] - Var 0 (mse_xsm): 46960723.3333
[val] - Var 0 (rmse_xsm): 6842.1056
[val] - Var 0 (mae_xsm): 5413.2221

[val] - Var 1 (mse_xo): 415179328.0000
[val] - Var 1 (rmse_xo): 20286.9431
[val] - Var 1 (mae_xo): 10519.7789
[val] - Var 1 (mse_xsm): 378619753.5556
[val] - Var 1 (rmse_xsm): 18818.1416
[val] - Var 1 (mae_xsm): 10294.9929

[val] - Var 2 (mse_xo): 82785.1806
[val] - Var 2 (rmse_xo): 287.7181
[val] - Var 2 (mae_xo): 242.5406
[val] - Var 2 (mse_xsm): 92043.9106
[val] - Var 2 (rmse_xsm): 302.9867
[val] - Var 2 (mae_xsm): 259.4178

[val] - Var 3 (mse_xo): 109381814.2222
[val] - Var 3 (rmse_xo): 10416.7309
[val] - Var 3 (mae_xo): 8406.3766
[val] - Var 3 (mse_xsm): 100801006.2222
[val] - Var 3 (rmse_xsm): 10038.7219
[val] - Var 3 (mae_xsm): 8017.5098

[val

/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XO] - Phase: test Var: 8:
[[5265    0]
 [2119    0]]


/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XSM] - Phase: test Var: 8:
[[604   0]
 [204   0]]


/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XO] - Phase: test Var: 9:
[[4194    0]
 [3135    0]]


/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XSM] - Phase: test Var: 9:
[[505   0]
 [358   0]]


/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XO] - Phase: test Var: 8:
[[336   0]
 [124   0]]


/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XSM] - Phase: test Var: 8:
[[33  0]
 [19  0]]


/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XO] - Phase: test Var: 9:
[[331   0]
 [131   0]]


/export/usuarios01/icmora/envs/conda_envs/test1/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Conf Matrix [XSM] - Phase: test Var: 9:
[[30  0]
 [20  0]]
CPU times: user 1min 8s, sys: 10.6 s, total: 1min 19s
Wall time: 1min 27s


In [3]:
%%time

vqvae_training(model_route="/export/usuarios01/icmora/deploymentVQVAE/api_test/results_finetune/fine_tune1", 
               data_route="~/data/eb2/daily_summary_eb2prod.csv",
               hyperparameters = {"num_epochs_vqvae":1, "train_batch_size":512}
)

/export/usuarios01/icmora/deploymentVQVAE/new_way/api_utils.py:144: DtypeWarning: Columns (55) have mixed types. Specify dtype option on import or set low_memory=False.
  df_ = pd.read_csv(original_data_path)


Model set to train on GPU: 0 for model: a0_1760967503 started. Preparing data loaders.

self.dataset.columns =
array(['user', 'date_time', 'service', 'sleep_start', 'location_distance',
       'location_time_home', 'sleep_duration', 'activity_walking',
       'app_usage_total', 'location_clusters_count', 'steps_steps_total',
       'weekend', 'practiced_sport'], dtype=object)

self.dataset.dtypes =
user                                int64
date_time                  datetime64[ns]
service                           float64
sleep_start                       float64
location_distance                 float64
location_time_home                float64
sleep_duration                    float64
activity_walking                  float64
app_usage_total                   float64
location_clusters_count           float64
steps_steps_total                 float64
weekend                             int64
practiced_sport                   float64
dtype: object

self.dataset.shape =
(164172, 13)


S

/export/usuarios01/icmora/deploymentVQVAE/new_way/api_utils.py:705: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  bce_loss_functions = [torch.nn.BCEWithLogitsLoss(pos_weight=torch.tensor(pos_weights[i], device=device), reduction="none")


Conf Matrix [XO] - Phase: train Var: 8:
[[23283  4783]
 [  916 10074]]
Conf Matrix [XSM] - Phase: train Var: 8:
[[2554  499]
 [ 531  752]]
Conf Matrix [XO] - Phase: train Var: 9:
[[14214  8969]
 [ 2259 13527]]
Conf Matrix [XSM] - Phase: train Var: 9:
[[1636 1018]
 [ 480 1289]]
[train]   <loss> reco: 1.1009 | latent: 0.2853 | overall: 1.1722

[train] - Var 0 (mse_xo): 13760683.0000
[train] - Var 0 (rmse_xo): 3709.5396
[train] - Var 0 (mae_xo): 2854.6248
[train] - Var 0 (mse_xsm): 43182136.0000
[train] - Var 0 (rmse_xsm): 6571.3115
[train] - Var 0 (mae_xsm): 5168.1787

[train] - Var 1 (mse_xo): 8752311296.0000
[train] - Var 1 (rmse_xo): 93553.7891
[train] - Var 1 (mae_xo): 12233.5557
[train] - Var 1 (mse_xsm): 483452384.0000
[train] - Var 1 (rmse_xsm): 21987.5508
[train] - Var 1 (mae_xsm): 11050.3965

[train] - Var 2 (mse_xo): 97501.8359
[train] - Var 2 (rmse_xo): 312.2528
[train] - Var 2 (mae_xo): 251.5490
[train] - Var 2 (mse_xsm): 117985.1016
[train] - Var 2 (rmse_xsm): 343.4896
[trai